# Generated by Django 5.2.5 on 2025-09-14 02:46

import app_cbt.models
import ckeditor_uploader.fields
import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengguna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('Nama', models.CharField(max_length=100)),
                ('Tikatan_Satuan_Lembaga', models.CharField(choices=[('SD/MI', 'SD/MI'), ('SMP/MTS', 'SMP/MTS'), ('SMA/MA', 'SMA/MA')], default='', max_length=30)),
                ('auto_password', models.CharField(blank=True, max_length=50, null=True)),
                ('is_siswa', models.BooleanField(default=False, verbose_name='Siswa')),
                ('Nama_User', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kelas', models.CharField(max_length=2, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pengguna',
            name='Kelas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas'),
        ),
        migrations.CreateModel(
            name='KurikulumLembaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kurikulum', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=False)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lembaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Lembaga', models.CharField(max_length=100)),
                ('Ketua_panitia', models.CharField(max_length=100)),
                ('NIP', models.CharField(blank=True, max_length=30, null=True)),
                ('NPSN', models.CharField(max_length=8)),
                ('Alamat', models.TextField()),
                ('Tikatan_Satuan_Lembaga', models.CharField(choices=[('SD/MI', 'SD/MI'), ('SMP/MTS', 'SMP/MTS'), ('SMA/MA', 'SMA/MA')], default='', max_length=30)),
                ('status', models.BooleanField(default=True)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('kurikulum_lebaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kurikulumlembaga')),
            ],
        ),
        migrations.AddField(
            model_name='kelas',
            name='Nama_Lembaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga'),
        ),
        migrations.AddField(
            model_name='pengguna',
            name='Nama_Lembaga',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga'),
        ),
        migrations.CreateModel(
            name='Matapelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nama_Mapel', models.CharField(max_length=100)),
                ('Nama_Lembaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga')),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rombel_kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rombel', models.CharField(max_length=5)),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas')),
                ('Nama_Lembaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga')),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pengguna',
            name='Rombel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cbt.rombel_kelas'),
        ),
        migrations.CreateModel(
            name='SEMESTER',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semester', models.CharField(choices=[('Genap', 'Genap'), ('Ganjil', 'Ganjil')], default='', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SetingSoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kode_Soal', models.CharField(default=app_cbt.models.buat_nomor_baru, editable=False, max_length=10)),
                ('aktif', models.BooleanField(default=False)),
                ('waktu_aktif', models.DateTimeField(blank=True, null=True)),
                ('durasi_menit', models.PositiveIntegerField()),
                ('arsip_soal', models.BooleanField(default=False)),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas')),
                ('Mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.matapelajaran')),
                ('Nama_Lembaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga')),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.semester')),
            ],
            options={
                'ordering': ['Kelas_id'],
            },
        ),
        migrations.CreateModel(
            name='Soal_Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nomor', models.IntegerField()),
                ('Soal', ckeditor_uploader.fields.RichTextUploadingField()),
                ('A', ckeditor_uploader.fields.RichTextUploadingField()),
                ('B', ckeditor_uploader.fields.RichTextUploadingField()),
                ('C', ckeditor_uploader.fields.RichTextUploadingField()),
                ('D', ckeditor_uploader.fields.RichTextUploadingField()),
                ('Kunci_Jawaban', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default=0, max_length=1)),
                ('Nilai', models.PositiveIntegerField(blank=True, null=True)),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas')),
                ('Kode_Soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.setingsoal')),
                ('Mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.matapelajaran')),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TahunPelajaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tahun_Pelajaran', models.CharField(max_length=9)),
                ('status', models.BooleanField(default=False)),
                ('tanggal_penetapan', models.DateField(default=django.utils.timezone.now)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.semester')),
            ],
        ),
        migrations.AddField(
            model_name='setingsoal',
            name='Tahun_Pelajaran',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.tahunpelajaran'),
        ),
        migrations.CreateModel(
            name='DaftarNilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas')),
                ('Nama_Lembaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.lembaga')),
                ('Mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.matapelajaran')),
                ('Rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.rombel_kelas')),
                ('Semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.semester')),
                ('Tahun_Pelajaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.tahunpelajaran')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jawaban', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True)),
                ('Jawaban_Benar', models.BooleanField(default=False)),
                ('Nilai_Siswa', models.PositiveIntegerField(blank=True, null=True)),
                ('Waktu_Mulai', models.DateTimeField(auto_now_add=True)),
                ('Waktu_Selesai', models.DateTimeField(blank=True, null=True)),
                ('Terakhir_Diubah', models.DateTimeField(auto_now=True)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.kelas')),
                ('Rombel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.rombel_kelas')),
                ('Kode_Soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.setingsoal')),
                ('Nomor_Soal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.soal_siswa')),
            ],
            options={
                'unique_together': {('Nama_User', 'Kode_Soal', 'Nomor_Soal')},
            },
        ),
    ]
