# Generated by Django 5.2.5 on 2025-11-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lembaga',
            name='desa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lembaga',
            name='kabupaten',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lembaga',
            name='kecamatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lembaga',
            name='provinsi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lembaga',
            name='tanggal_mulai_ujian',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lembaga',
            name='Alamat',
            field=models.TextField(max_length=500),
        ),
    ]
