# Generated by Django 5.2.1 on 2025-08-13 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lembaga',
            old_name='satatus',
            new_name='status',
        ),
    ]
