# Generated by Django 5.2.5 on 2025-12-20 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jenis_Ujian', models.CharField(choices=[('UTS', 'Ujian Tengah Semester'), ('UAS', 'Ujian Akhir Semester'), ('UKK', 'Ujian Kenaikan Kelas'), ('UJIAN_AKHIR', 'Ujian Akhir')], default='', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('Nama_User', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='setingsoal',
            name='Jenis_Ujian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cbt.jenis_ujian'),
        ),
    ]
