# Generated by Django 5.2.1 on 2025-08-02 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daftarnilai',
            name='Semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cbt.semester'),
        ),
    ]
