# Generated by Django 5.2.5 on 2025-11-25 21:57

import app_cbt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0002_lembaga_desa_lembaga_kabupaten_lembaga_kecamatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setingsoal',
            name='Kode_Soal',
            field=models.CharField(blank=True, default=app_cbt.models.buat_nomor_baru, editable=False, max_length=5, null=True, unique=True),
        ),
    ]
