# Generated by Django 5.2.5 on 2025-12-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0002_alter_pengguna_kelas_alter_pengguna_rombel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='Jawaban',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], db_index=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='pengguna',
            name='Nama',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
