# Generated by Django 5.2.5 on 2025-12-20 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0002_jenis_ujian_setingsoal_jenis_ujian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setingsoal',
            old_name='Jenis_Ujian',
            new_name='jenis_ujian',
        ),
    ]
