# Generated by Django 5.2.1 on 2025-08-15 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0002_rename_satatus_lembaga_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengguna',
            name='auto_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
