# Generated by Django 5.2.5 on 2025-12-20 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0003_rename_jenis_ujian_setingsoal_jenis_ujian'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarnilai',
            name='jenis_ujian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_cbt.jenis_ujian'),
        ),
    ]
