# Generated by Django 5.2.1 on 2025-08-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0003_alter_setingsoal_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='daftarnilai',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
