# Generated by Django 5.2.5 on 2025-09-12 13:19

import app_cbt.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cbt', '0005_alter_setingsoal_kode_soal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setingsoal',
            name='Kode_Soal',
            field=models.CharField(default=app_cbt.models.buat_nomor_baru, editable=False, max_length=6),
        ),
    ]
